site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: deep purple
    scheme: slate

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - blog

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Code Docs:
    - Java: coding/my-first-java-file.md
  - About:
    - Current Projects: about/projects.md
    - About Me: about/about.md
    - Childhood: about/childhood.md
  - Tags: tags.md
  - Blog:
    - blog/index.md
